# Generated by Django 5.2 on 2026-03-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemorden',
            name='descripcion_snapshot',
        ),
        migrations.AddField(
            model_name='itemorden',
            name='imagen_snapshot',
            field=models.ImageField(blank=True, null=True, upload_to='snapshots/'),
        ),
    ]
