# Generated by Django 5.2 on 2026-03-21 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_remove_itemorden_descripcion_snapshot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrito',
            name='fecha_añadido',
        ),
        migrations.AlterField(
            model_name='itemcarrito',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_carrito', to='tienda.carrito'),
        ),
    ]
