# Generated by Django 5.2 on 2026-03-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_remove_itemcarrito_fecha_añadido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcarrito',
            name='precio_unidad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
