# Generated by Django 5.2 on 2026-03-21 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_alter_itemcarrito_precio_unidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencompra',
            name='id_compra',
        ),
    ]
