# Generated by Django 5.2 on 2026-03-21 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_remove_ordencompra_id_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencompra',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='fecha_orden',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='imagen_comprobante',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='moneda_pago',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='monto_final_pago',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='nota_admin',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='subtotal_usd',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='user',
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_carrito', to='tienda.ordencompra'),
        ),
        migrations.AlterField(
            model_name='itemcarrito',
            name='carrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_carrito', to='tienda.carrito'),
        ),
        migrations.DeleteModel(
            name='ItemOrden',
        ),
    ]
