# Generated by Django 5.2 on 2026-04-02 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversacion',
            old_name='fecha_creacion',
            new_name='creado',
        ),
        migrations.RenameField(
            model_name='conversacion',
            old_name='fecha_modificacion',
            new_name='modificado',
        ),
    ]
